import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProviders from "@/redux/ReduxProvider";
import TopMenu from "@/components/TopMenu";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import NextAuthProviders from "@/providers/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          <NextAuthProviders session={session}>
            <TopMenu/>
            {children}
          </NextAuthProviders>
        </ReduxProviders>
        
       
        </body>
    </html>
  );
}
